INSERT INTO job VALUES(667,'CLERK');
INSERT INTO job VALUES(668,'STAFF');
INSERT INTO job VALUES(669,'ANALYST');
INSERT INTO job VALUES(670,'SALESPERSON');
INSERT INTO job VALUES(671,'MANAGER');
INSERT INTO job VALUES(672,'PRESIDENT');
